image: node:12.13.0

stages:
  - test

before_script:
  - yarn

lint:
  stage: test
  except:
    - master
  script:
    - yarn lint

lint:code-formatter:
  stage: test
  except:
    - master
  script:
    - yarn code-formatter-check

lint:types:
  stage: test
  except:
    - master
  script:
    - yarn types-check

pages:
  only:
    - master
  script:
    - yarn build
    - mkdir public
    - mv dist/* public/
    - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
